CREATE TABLE "movies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "imdb_id" varchar(20) UNIQUE,
  "title" varchar(500) NOT NULL,
  "year" integer,
  "rated" varchar(20),
  "runtime_minutes" integer,
  "rating" decimal(3,1),
  "vote_count" integer,
  "plot" text,
  "poster_url" text,
  "release_date" date,
  "language" varchar(100),
  "country" varchar(100),
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" datetime
);

CREATE TABLE "genres" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "movie_genres" (
  "movie_id" integer,
  "genre_id" integer
);

CREATE TABLE "people" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "imdb_name_id" varchar(20) UNIQUE,
  "name" varchar(255) NOT NULL,
  "birth_year" integer,
  "death_year" integer,
  "bio" text,
  "photo_url" text,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" varchar(200)
);

CREATE TABLE "movie_people" (
  "movie_id" integer,
  "person_id" integer,
  "role_id" integer,
  "character_name" varchar(200),
  "ordering" integer DEFAULT 0
);

CREATE TABLE "box_office" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movie_id" integer,
  "release_version" varchar(50) DEFAULT 'Theatrical',
  "region" varchar(50) DEFAULT 'Worldwide',
  "us_canada_gross" bigint,
  "opening_weekend" bigint,
  "budget" bigint,
  "worldwide_gross" bigint,
  "currency" varchar(10) DEFAULT 'USD',
  "updated_at" datetime
);

CREATE TABLE "awards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movie_id" integer,
  "award_name" varchar(255) NOT NULL,
  "category" varchar(200),
  "year" integer,
  "won" boolean DEFAULT false,
  "ceremony_date" date,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "user_ratings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movie_id" integer,
  "user_id" varchar(100) NOT NULL,
  "rating" decimal(3,1) NOT NULL,
  "review" text,
  "rating_date" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE UNIQUE INDEX ON "movie_genres" ("movie_id", "genre_id");

CREATE UNIQUE INDEX ON "movie_people" ("movie_id", "person_id", "role_id");

CREATE UNIQUE INDEX ON "box_office" ("movie_id", "release_version", "region");

CREATE UNIQUE INDEX ON "user_ratings" ("movie_id", "user_id");

ALTER TABLE "movie_genres" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movie_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movie_people" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movie_people" ADD FOREIGN KEY ("person_id") REFERENCES "people" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movie_people" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "box_office" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "awards" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_ratings" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") DEFERRABLE INITIALLY IMMEDIATE;
